<?php

/** @var $block \RockSolidSoftware\BookRental\Block\CustomerBooksBlock */

$customerBooks = $block->customerBooks();

?>

<div id='book-rental'>
    <h2><?= __('Your rented books') ?></h2>

    <?php if (empty($customerBooks)): ?>
        <?= __('You currently have no books rented') ?>
        <br/><br/>
        <a href='<?= $block->getUrl('book_rental/index/index') ?>'><?= __('See books available to rent') ?></a>
    <?php else: ?>
        <?php /** @var \RockSolidSoftware\BookRental\API\Data\CustomerBookInterface $customerBook */ ?>
        <?php foreach ($customerBooks as $customerBook): ?>
            <div class='book-rent-entry'>
                <div class='book-rent-entry__title'>
                    <?= $customerBook->getBookAuthor() ?>
                </div>
                <div class='book-rent-entry__author'>
                    <?= $customerBook->getBookTitle() ?>
                </div>
                <div class='book-rent-entry__since'>
                    <?= __('Rented since') ?>: <?= (new \DateTime($customerBook->getCreatedAt()))->format('Y-m-d H:i') ?>
                </div>
                <div class='book-rent-entry__status'>
                    <a href='<?= $block->getUrl('book_rental/rent/book', [
                        'slug' => $customerBook->getBookSlug(),
                    ]) ?>'><?= __('Return book') ?></a>
                </div>
            </div>
        <?php endforeach ?>
    <?php endif ?>
</div>