<?php

/** @var $block \RockSolidSoftware\BookRental\Block\BookBlock */

$book = $block->getBook($block->getRequest()->getParam('slug'));

?>

<div id='book-rental'>
    <div class='book-show-box'>
        <h4><?= $book->getAuthor() ?></h4>
        <h2><?= $book->getTitle() ?></h2>

        <div class='book-status'>
            <div class='book-status-free'>
                <a href='<?= $block->getUrl('book_rental/rent/returnBook', [
                    'slug' => $book->getSlug(),
                ]) ?>'><?= __('Return this book') ?></a>
            </div>
        </div>
    </div>
</div>